apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-spring-boot-app
  description: A simple Spring Boot application
  tags:
    - springboot
spec:
  type: service
  lifecycle: production
  owner: team-xyz
  repo: https://github.com/Harpreet386/spring-boot-api
