openapi: 3.0.1
info:
  title: Demo API
  description: This is a demo API documentation
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/person/:
    get:
      tags:
        - person-controller
      summary: Get all persons
      operationId: getAllPersons
      responses:
        "200":
          description: Found the persons
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
        "404":
          description: Persons not found
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
    post:
      tags:
        - person-controller
      summary: Add a new person
      operationId: addPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Person"
  "/api/person/{id}":
    get:
      tags:
        - person-controller
      summary: Get a person by ID
      operationId: getPersonById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/Person"
components:
  schemas:
    Person:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        age:
          type: integer
          format: int32
