apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: spring-boot-template
  description: A template for creating Spring Boot applications
spec:
  type: service
  owner: team-a
  parameters:
    - title: Service Name
      description: The name of the Spring Boot service to create
      type: string
  path: /templates/spring-boot-template
  templater: express
  repository:
    url: https://github.com/Harpreet386/spring-boot-api
