#apiVersion: backstage.io/v1alpha1
#kind: Component
#metadata:
#  name: spring-boot-api
#  title: spring-boot-api
#  annotations:
#    github.com/project-slug: Harpreet386/spring-boot-api
#  tags:
#    - spring-boot
#    - java
#    - maven
#spec:
#  type: service
#  owner: Harpreet386
#  lifecycle: experimental

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: person-service
  description: "Spring Boot Person API"
  tags:
    - spring-boot
spec:
  type: service
  lifecycle: production
  owner: team-xyz
  system: person-system
  api:
    - target: http://localhost:8080/api   # Link to your API endpoint
  annotations:
    #backstage.io/openapi: "https://github.com/your-username/your-repo/blob/main/api/openapi.yaml"
